### ISSUE TITLE
feature: save roulette options

### ISSUE THREAD

**Issue by nutpantz** [m-i-n-a-r/randomix#11]
It would be great if there was a save option of choices for long term .

**Comment by m-i-n-a-r** [comment]
You mean something different from the default "recent options" button? Maybe a button to "pin" a recent list?

**Comment by nutpantz** [comment]
Like maybe 3 or 5 favorites. Well at least 3 different favorites

**Comment by m-i-n-a-r** [comment]
in 44c27f79aa8e51ef419f36601805dbb420c377e8, i changed the recent list behavior: tap to restore, swipe to delete, long press to "pin" a set of options. Pinned sets won't be automatically deleted and are highlighted!
