### ISSUE TITLE
enhancement: speed setting for magic ball response

### ISSUE THREAD

**Issue by Rially** [m-i-n-a-r/randomix#15]
Hi,
the app is wonderful. 
Now I do not have to ask Google to throw a coin.
As for the magic ball, could you perhaps make the scroll speed of the response adjustable? Or give an option to speed it up by tapping on it?
Some of the sentences are rather long.

**Comment by m-i-n-a-r** [comment]
Hi, I'm glad you like the app! Yep i can do that, I'll reduce the text size
or make the scroll faster in the next update.

Have a great day!

m.i.n.a.r.

Il ven 15 gen 2021, 02:44 Ria W. <notifications@github.com> ha scritto:

**Comment by m-i-n-a-r** [comment]
I decreased the text size in 27ae3c2bccfc0842ca5b9f5ce220f43f10c83694, it should work. Regarding the speed, changing it is not possible by default, so i'm trying this solution first.
