### ISSUE TITLE
More dice, different dice

### ISSUE THREAD

**Issue by dalaeance** [m-i-n-a-r/randomix#18]
I'm thinking it would be cool if we could use the Dice functionality to play games using D10s (and maybe also D4, D8, D12, D20, D48, D100, and D120 dice).

It would also be nice if we could select the type & amount of dice on the fly, instead of having to go into the settings. If it's doable, I think up to a maximum of 10 dice vs the current 3 dice.

Thanks for making this app. I'm an indecisive person, and finding it in F-Droid made my day!

**Comment by m-i-n-a-r** [comment]
The dices are created with a lot of animated vector drawables, and despite their simplicity, adding more faces means redoing every animation from scratch for every type. Not impossible of course, but it's a very long process. What I can do instead, in a reasonable amount of time at least, is allowing more than three dices. 
I'll try to increase this number up to 9 or 10 in the next update!

**Comment by dalaeance** [comment]
Thanks! I appreciate it. And, of course, whatever's easiest for you. Having other types of dice is just a convenience thing, so no rush. If you do choose to eventually add other dice types, please prioritize D10s. :slightly_smiling_face:

**Comment by m-i-n-a-r** [comment]
in ccdaf256205c717163153ba4eb4c24268161f093 and following commits i added an option to use up to 10 dice, plus a 3v3 mode for games like "Risk". I'm aware is just a part of what you requested, but adding different kind of dice is very tricky at the moment. I'll reopen the issue for any other update related to this request of course 😃 thanks for the suggestion!

**Comment by dalaeance** [comment]
Thanks for the update! And for the effort you're putting in. 😊
