### ISSUE TITLE
Set default tab or remember alst used one

### ISSUE THREAD

**Issue by Ungoose** [m-i-n-a-r/randomix#19]
I use the app almost exclusively for dice rolls and rarely ever touch the roulette, so I wonder if you could add a setting to choose a default tab or go to the last used tab at startup? Thanks!

**Comment by m-i-n-a-r** [comment]
Yep, i can do that. I'll just need some time!

**Comment by Ungoose** [comment]
It'd be great, thanks! I really like the app, both visually and feature-wise (and of course that it's FOSS).

**Comment by m-i-n-a-r** [comment]
Done in 0be55b28fa43929c02b04da93a5e6127ce47447b and following commit. Now the app remembers the last opened tab and should have a better navigation in general. I should release the update quite soon. Thanks for the suggestion!
