### ISSUE TITLE
Auto-rotation not respecting system setting

### ISSUE THREAD

**Issue by SeerLite** [m-i-n-a-r/randomix#22]
Hi!

Auto-rotation happens whether or not it's enabled as a system setting. This makes it really annoying to use when lying down. The app should use the system setting and not rotate on its own.

Thank you for the app. It's very pleasant to use :)

**Comment by m-i-n-a-r** [comment]
I'm glad you like the app! Regarding this issue, are you sure you're running the latest version available? This was a bug months ago, but it should be fixed now, and it doesn't happen on my test devices (Oneplus One, Oneplus 7 pro, Xiaomi mi 5x). If you take a look at the manifest, [here](https://github.com/m-i-n-a-r/randomix/blob/master/app/src/main/AndroidManifest.xml), you can notice that the orientation for the main part of the app is "fullUser": this should mean that when the rotation is locked, the app won't rotate, while if the rotation is enabled, the app will rotate in every possible orientation, even upside down :)

**Comment by SeerLite** [comment]
Ok this is really weird but now I'm testing it again and rotation is working correctly (so no rotation). It was, and still is, the latest version. I only installed it yesterday from F-Droid.

Maybe I accidentally pressed the rotation button that shows up on LineageOS and assumed the app auto-rotated or something. Sorry, I'll let you know if it happens again.
