### ISSUE TITLE
Roulette limited to 15 options

### ISSUE THREAD

**Issue by TheLastProject** [m-i-n-a-r/randomix#23]
Hey,

I quite like this app, but I sadly can't use Roulette Mode for my use case because it is limited to 15 options.

Let me describe my use case:
Every Saturday, I go and play an online game with some friends, with several game modes each having their own maps. To keep the evening varied, we like to play every game mode and each time play a random map.

However, a few of the game modes have more than 15 maps (one mode has almost 30 maps) so this means I can't put the random map selection of that mode into the Roulette feature.

Any chance this limit could be increased, especially given 2 of the recent options (A-Z Letters and 1-100) both use more than 15 entries?

**Comment by m-i-n-a-r** [comment]
Yep, no problem. The limit was just to keep the recent options menu clean, but i can surely increase it to something like 30. I'll do it in the next update!

**Comment by m-i-n-a-r** [comment]
Limit increased to 30 in 8556497c1ca06305a6568b40ccf3571fe905f4a0. I'll update the app in the next few days!
