### ISSUE TITLE
Add country randomizer

### ISSUE THREAD

**Issue by ghost** [m-i-n-a-r/randomix#25]
Thank you for beautiful app! I suggest to add country randomizer with country names and its flags. Sometimes it may be userful.

**Comment by m-i-n-a-r** [comment]
That's not an easy feature to implement properly, but I'll see what I can do in the upcoming updates!

**Comment by m-i-n-a-r** [comment]
I can't do this at the moment (issues with translations and ui) so i'll close this issue, but i'll keep it in my to-do list 👍
