### ISSUE TITLE
Random number generator

### ISSUE THREAD

**Issue by tbmny** [m-i-n-a-r/randomix#26]
A cool addition would be an RNG, where you can choose a range and generate one or more numbers from that range.

**Comment by m-i-n-a-r** [comment]
Sorry for the late reply, i missed this issue 😄 I'm working on a custom range feature!

**Comment by m-i-n-a-r** [comment]
Done in db2fb6e448ff0d5cc7d32071fc15a15df7107e62 and following commits, it will be available with the next release (24/48h from now). Thanks!
