### ISSUE TITLE
Sice menu typo

### ISSUE THREAD

**Issue by candroid-man** [m-i-n-a-r/randomix#27]
Small little thing. In the dice menu it says you can only do 1 to 3 dice at one time but in the settings you are able to do a lot more than 3

**Comment by m-i-n-a-r** [comment]
It will be fixed in the next update, thanks for pointing that out!

**Comment by m-i-n-a-r** [comment]
Fixed in b0d2900e6880cd755c864f71eac31ba7ce293e11 and available in the next release (it should be ready in 24/48h)
