### ISSUE TITLE
Please implement backups for Seedvault

### ISSUE THREAD

**Issue by meyou69** [m-i-n-a-r/randomix#32]
Starting from Android 12, you can configure on your phone a Seedvault backup, in which, after writing down a series of randomly chosen English words, you can start backing up all your apps and app data from your device regularly to a Seedvault server somewhere.

I did this on my LineageOS device and, after doing so, I checked the list of apps that had been backed up (as well as the apps which haven't) and, to my surprise, I've found randomix to not have backed up anything. Apparently the app reported "No data for backup".

I would like for this to change, especially since I have saved in the app a long past history list of roulette options which, if my phone was ever lost or stolen, I would like to be restored on a new device from my backups.

Can you please implement this?

**Comment by m-i-n-a-r** [comment]
I'd be glad to do it, i just have tu understand what SeedVault is and how it works. I'll see what i can do, thanks for suggesting it!

**Comment by m-i-n-a-r** [comment]
Should be fixed in 17c493359241c25354c459ebedfffaaff030056a , i can't test but i did my best.

**Comment by meyou69** [comment]
Thank you!
