### ISSUE TITLE
Document entropy source

### ISSUE THREAD

**Issue by rusty-snake** [m-i-n-a-r/randomix#33]
AFAICTY `java.util.Random` is used as RNG. `java.util.Random` isn't cryptographically secure. It would be nice if this is documented in the README/description.

**Comment by m-i-n-a-r** [comment]
I don't see why this is a concern in this kind of app. I mean, somebody could predict or manipulate the result, but that's not a problem I guess. By the way, if you want to suggest an alternative method/algorithm, every suggestion is well appreciated 👍

**Comment by rusty-snake** [comment]
1. The idea was to use it for diceware password generation.
2. I'm not deep in the java api but maybe `java.security.SecureRandom` works.

**Comment by m-i-n-a-r** [comment]
I'll see what i can do 😄
