### ISSUE TITLE
The themed app icon is off-center

### ISSUE THREAD

**Issue by vytskalt** [m-i-n-a-r/randomix#35]
![image](https://user-images.githubusercontent.com/35194709/208496451-5be6951a-564f-49e8-8f5b-5cc91bf42205.png)

**Comment by m-i-n-a-r** [comment]
Wow, i didn't notice it 😕 i'll fix it in the next update!

**Comment by m-i-n-a-r** [comment]
Done in 97c08716dac87bc9490a2bf23a98dd1a15edc359 I edited the logo to also look a little better 😄
