### ISSUE TITLE
optional setting to disable descriptions

### ISSUE THREAD

**Issue by mmguero** [m-i-n-a-r/randomix#4]
Very cool app! I've got a simple suggestion: put a toggle in "settings" to be able to turn off the descriptions at the top of each page (e.g., "Flipping a coin is easy, but...", etc.). Once you've used the app for a while you know what the pages do and being able to toggle those descriptions on or off would allow for a cleaner look.

**Comment by m-i-n-a-r** [comment]
Yep i agree with you! I'll do that in the next update, thanks!

**Comment by m-i-n-a-r** [comment]
Option added in e4e38f65df11594adb46e5cf17b812fcfc101570 
Thanks for the advice 👍
