### ISSUE TITLE
Language translation offer

### ISSUE THREAD

**Issue by SecularSteve** [m-i-n-a-r/randomix#46]
I offer to translate the app into the following languages:

-Dutch
-British English
-Bosnian
-Croatian
-Serbian

I'm also proficient at:
-German

**Comment by m-i-n-a-r** [comment]
Thanks, i'd really appreciate it! Refer to https://crwd.in/randomix and to the wiki if you need help, or send me an email. In the meantime, i updated the Crowdin project to support the languages you mentioned. I already have a German translation, but the others are missing. I'll close the issue, just to keep things ordered!

**Comment by SecularSteve** [comment]
You'd be happy to know that I'm finished with all of the translations.

**Comment by SecularSteve** [comment]
You'd be happy to know that I'm finished with all of the translations.

**Comment by m-i-n-a-r** [comment]
Thanks a lot! I'll review every translation in the next few days and update the app. Of course, you will be credited!
