### ISSUE TITLE
Configurable chances in Roulette page?

### ISSUE THREAD

**Issue by pumguy** [m-i-n-a-r/randomix#5]
I think it's more common the case that we don't want each options in roulette to have the equal chance to be chosen, so I suggest making chances of each options configurable, or simply allowing duplicated options. 
Suggested method: long press an option to create a copy of it. 
Thanks for making this amazing app!

**Comment by m-i-n-a-r** [comment]
Well it's a good suggestion, the simplest way is probably letting the user insert the same option two or more times, maybe enabling it with an option. I'll see what I can do in the next update, thanks!

**Comment by m-i-n-a-r** [comment]
With 9f959c5be08d317206a7bcd83ee783306c77c479 i added an option to allow duplicate options in roulette. Thanks for the advice!
