### ISSUE TITLE
Suggestion 

### ISSUE THREAD

**Issue by electr1fy0** [m-i-n-a-r/randomix#52]
The app would look a lot better if the icon can be changed to a modern flat one.
Same design but flat and basic colors (no gradient).

Also, remove the gradient splash screen as it does not match with the beautiful MD3 UI of this app.

**Comment by m-i-n-a-r** [comment]
Like i wrote in the description, Randomix follows the material guidelines just partially, and the flat icon is already there for Android 13+ (the monochrome icon to be precise). The splash screen doesn't have a gradient. The only gradient is in the intro page, shown only once! Thanks for the advice!
