### ISSUE TITLE
Adaptive icon does not adapt properly

### ISSUE THREAD

**Issue by Commenter25** [m-i-n-a-r/randomix#59]
The current icon is cropped into a circle. This defeats the point of adaptive icons, which is that they can be masked into any shape. This causes inconsistency on any device not using circle icons. The background gradient should extend to the entire source image, and the system should crop it from there. https://developer.android.com/develop/ui/views/launch/icon_design_adaptive

![An image of the current icon when using rounded square icons, next to icons with properly adaptive icons](https://github.com/m-i-n-a-r/randomix/assets/35016761/81cba1dd-4030-4048-909a-6a8a935d4912)

**Comment by m-i-n-a-r** [comment]
Yep, it makes sense. This is not a bug, strictly speaking, because I used a white bg to preserve the original appearance of the icon, but I'll try to improve it!

**Comment by m-i-n-a-r** [comment]
Done in 866ed62f9ec1ae7c9827ee393803fc6bdcf04bfe I'll release the update once the new translation updates are ready!
