### ISSUE TITLE
Random number generator

### ISSUE THREAD

**Issue by Ryakna** [m-i-n-a-r/randomix#8]
First of all, thank you very much for the awesome app.

I suggest an option to generate a random number between a predefined range chosen by the user.

**Comment by m-i-n-a-r** [comment]
I'm not sure where to add this option, but it could be useful. I'll se what i can do!

**Comment by Ryakna** [comment]
@m-i-n-a-r Thanks for considering it.

I guess a random number generator would warrant a separate fifth option along with the current four.

Regarding this suggestion, the idea came when I was using the app to choose a random movie to watch with my girlfriend from a watchlist with hundreds of entries and none of the other available options would be feasible. With a generator, I could configure it to choose a random number between say 1 and 600 and it would be perfect for that.

**Comment by m-i-n-a-r** [comment]
Ok, I'll work on that for the next update! The max number of modes in the bottom bar is five though, so I'll have to remove une of the modes or change how navigation works 🤔

**Comment by m-i-n-a-r** [comment]
I know it's a bit limited, but in 4e70c814f50948d93197d352d0b9993f6f76562f i added some presets in the roulette, such as letters and 1-100 numbers. I will add more in future updates. I'm trying to keep the app as clean as possible. Thanks for the suggestion!
