### ISSUE TITLE
AMOLED black theme

### ISSUE THREAD

**Issue by Ryakna** [m-i-n-a-r/randomix#9]
A new pure black theme for devices with AMOLED screens.

**Comment by m-i-n-a-r** [comment]
I don't have this option since my apps follow the material guidelines, i'll see if i can add an extra option to turn the dark grey to black 👍

**Comment by m-i-n-a-r** [comment]
I have no plan for an amoled theme at the time, i'm waiting for an official Google support to avoid messing up the app with a buggy black theme. I'll reopen this issue if i have updates though! :)
